# YAML = Yet another markup language

# keyname: value
# myapp:
#   service: practice-project
#   test1: script1
#   test: script2
#   myArray:
#     - key1: value1
#       keyrandom: valuerandom
#     - 2
#     - 3
#     - 4
#     - 5
# Multiline strings
# name: |
#   George
#   Connor
#   Alex
name: My first github action
on: [push]
jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14.17.0"
      - name: Install node_modules
        run: npm install
      - name: Build the project
        run: npm run build
      - name: Setup finish
        run: echo "Hurray!!!"
  test-app:
    needs: build-app
    runs-on: ubuntu-latest
    steps:
      - run: echo "Happy new year"
