# YAML = Yet another markup language

# keyname: value
# myapp:
#   service: practice-project
#   test1: script1
#   test: script2
#   myArray:
#     - key1: value1
#       keyrandom: valuerandom
#     - 2
#     - 3
#     - 4
#     - 5
# Multiline strings
# name: |
#   George
#   Connor
#   Alex
name: My first github action
on: [push]
jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: tree
